export const STUDY_CATEGORIES = [
  "BYGGINGENIØRER",
  "DATAINGENIØR/IT",
  "ELEKTROINGENIØRER",
  "ENERGI & MILJØ INGENIØR",
  "BIOTEKNOLOGI- OG KJEMIINGENIØR",
  "MASKINIGENIØRER",
  "ØKONOMI OG ADMINISTRASJON",
  "LEDELSE",
  "HUMAN RESOURCES",
];
